import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/patient-manager-component/theme-provider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "../../app/globals.css";
import { RoleGate } from "@/components/auth/role-gate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DocDashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <RoleGate allowedRole="Admin">
      <SessionProvider session={session}>
        <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="p-[2%]">
              {children}
            </div>
          </ThemeProvider>
        </body>
      </SessionProvider>
    </RoleGate>
  );
}
