import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/patient-manager-component/theme-provider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "../../app/globals.css";
import Nav, { SecondNav } from "@/components/DashboardUI/Nav";
import { cn } from "@/lib/utils";
import { RoleGate } from "@/components/auth/role-gate";
import { TheDocAvailabilty } from "@/actions/doctor.actions";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DocDashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  const isDocAvailable = await TheDocAvailabilty(session?.user.id!);
  return (
    <SessionProvider session={session}>
      <RoleGate allowedRole="Doctor">
        <div className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="p-[2%]">
              <SecondNav isDocAvailable={isDocAvailable!} />

              <div className="flex">
                <Nav />

                {children}
              </div>

              <Toaster />
            </div>
          </ThemeProvider>
        </div>
      </RoleGate>
    </SessionProvider>
  );
}
