import { Gender, UserRole } from "@prisma/client";
import { z } from "zod";

export const UserFormValidation = z.object({
  name: z
    .string()
    .min(2, "Name must be at least 2 characters")
    .max(50, "Name must be at most 50 characters"),
  email: z.string().email("Invalid email address"),
  phone: z
    .string()
    .refine((phone) => /^\+\d{10,15}$/.test(phone), "Invalid phone number"),
  password: z.string().min(3, {
    message: "Password is required",
  }),
});

export const PatientFormValidation = z.object({
  name: z
    .string()
    .min(2, "Name must be at least 2 characters")
    .max(50, "Name must be at most 50 characters"),
  email: z.string().email("Invalid email address"),
  phone: z
    .string()
    .refine((phone) => /^\+\d{10,15}$/.test(phone), "Invalid phone number"),
  password: z.string().min(3, {
    message: "Password is required",
  }),
  birthDate: z.coerce.date(),
  gender: z.enum([Gender.Male, Gender.Female, Gender.Other]),
  address: z
    .string()
    .min(5, "Address must be at least 5 characters")
    .max(500, "Address must be at most 500 characters"),
  occupation: z
    .string()
    .min(2, "Occupation must be at least 2 characters")
    .max(500, "Occupation must be at most 500 characters"),
  emergencyContactName: z
    .string()
    .min(2, "Contact name must be at least 2 characters")
    .max(50, "Contact name must be at most 50 characters"),
  emergencyContactNumber: z
    .string()
    .refine(
      (emergencyContactNumber) => /^\+\d{10,15}$/.test(emergencyContactNumber),
      "Invalid phone number"
    ),
  primaryPhysician: z.string().min(2, "Select at least one doctor"),
  insuranceProvider: z
    .string()
    .min(2, "Insurance name must be at least 2 characters")
    .max(50, "Insurance name must be at most 50 characters"),
  insurancePolicyNumber: z
    .string()
    .min(2, "Policy number must be at least 2 characters")
    .max(50, "Policy number must be at most 50 characters"),
  allergies: z.string().optional(),
  currentMedication: z.string().optional(),
  familyMedicalHistory: z.string().optional(),
  pastMedicalHistory: z.string().optional(),
  identificationType: z.string().optional(),
  identificationNumber: z.string().optional(),
  identificationDocumentUrl: z.string().min(2, "image url is required"),
  treatmentConsent: z
    .boolean()
    .default(false)
    .refine((value) => value === true, {
      message: "You must consent to treatment in order to proceed",
    }),
  disclosureConsent: z
    .boolean()
    .default(false)
    .refine((value) => value === true, {
      message: "You must consent to disclosure in order to proceed",
    }),
  privacyConsent: z
    .boolean()
    .default(false)
    .refine((value) => value === true, {
      message: "You must consent to privacy in order to proceed",
    }),
});

export const DoctorSchema = z.object({
  id: z.string().cuid().optional(), // Auto-generated by Prisma
  name: z.string().min(2, "Name must be at least 2 characters"),
  email: z.string().email("Invalid email address"),
  phone: z.string().min(7, "Phone number must be at least 7 digits"),
  gender: z.enum([Gender.Male, Gender.Female, Gender.Other]),
  birthDate: z.coerce.date(), // Coerce string to Date
  address: z.string().optional(),
  specialization: z.string().optional(),
  licenseNumber: z.string().min(1, "License number is required"),
  yearsOfExperience: z.coerce.number().optional(),
  education: z.string().optional(),
  hospitalAffiliation: z.string().optional(),
  isDocAvailable: z.boolean().default(true),
  role: z.enum([UserRole.Admin, UserRole.Doctor, UserRole.Patient]),
  image: z.string().url().optional(),
  password: z.string().min(8, "Password must be at least 8 characters"),
});

export const CreateAppointmentSchema = z.object({
  id: z.string().optional(),
  schedule: z.coerce.date(),
  reason: z
    .string()
    .min(2, "Reason must be at least 2 characters")
    .max(500, "Reason must be at most 500 characters"),
  note: z.string().optional(),
  doctorId: z.string().min(1, "Select at least one doctor"),
  cancellationReason: z.string().optional(),
});

export const ScheduleAppointmentSchema = z.object({
  doctorId: z.string().min(1, "Select at least one doctor"),
  schedule: z.coerce.date(),
  reason: z.string().optional(),
  note: z.string().optional(),
  cancellationReason: z.string().optional(),
});

export const CancelAppointmentSchema = z.object({
  doctorId: z.string().min(1, "Select at least one doctor"),
  schedule: z.coerce.date(),
  reason: z.string().optional(),
  note: z.string().optional(),
  cancellationReason: z
    .string()
    .min(2, "Reason must be at least 2 characters")
    .max(500, "Reason must be at most 500 characters"),
});

export function getAppointmentSchema(type: string) {
  switch (type) {
    case "create":
      return CreateAppointmentSchema;
    case "cancel":
      return CancelAppointmentSchema;
    default:
      return ScheduleAppointmentSchema;
  }
}

export const NewPasswordSchema = z.object({
  password: z.string().min(6, { message: "Minimum 6 characters required" }),
});

export const ResetSchema = z.object({
  email: z.string().email({ message: "Email is required" }),
});

export const LoginSchema = z.object({
  email: z.string().email({ message: "Email is required" }),
  password: z.string().min(1, {
    message: "Password is required",
  }),
  code: z.optional(z.string()),
});

export const SettingsSchema = z
  .object({
    name: z.optional(z.string()),
    isTwoFactorEnabled: z.optional(z.boolean()),
    role: z.enum([UserRole.Admin, UserRole.Patient]),
    email: z.optional(z.string().email()),
    password: z.optional(z.string().min(6)),
    newPassword: z.optional(z.string().min(6)),
  })
  .refine(
    (data) => {
      if (data.password && !data.newPassword) {
        return false;
      }

      if (data.newPassword && !data.password) {
        return false;
      }

      return true;
    },
    {
      message: "New password is required",
      path: ["newPassword"],
    }
  )

  .refine(
    (data) => {
      if (data.newPassword && !data.password) {
        return false;
      }

      if (data.password && !data.newPassword) {
        return false;
      }

      return true;
    },
    {
      message: "password is required",
      path: ["password"],
    }
  );

export const BloodTestSchema = z.object({
  patientName: z.string().min(1),
  patientId: z.string().min(1),
  testDate: z.coerce.date(),

  hemoglobin: z.coerce.number().min(0),
  hematocrit: z.coerce.number().min(0),
  wbcCount: z.coerce.number().min(0),
  rbcCount: z.coerce.number().min(0),
  platelets: z.coerce.number().min(0),
  mcv: z.coerce.number().min(0),
  mch: z.coerce.number().min(0),
  mchc: z.coerce.number().min(0),
  rdw: z.coerce.number().min(0),
  neutrophils: z.coerce.number().min(0),
  lymphocytes: z.coerce.number().min(0),
  monocytes: z.coerce.number().min(0),
  eosinophils: z.coerce.number().min(0),
  basophils: z.coerce.number().min(0),
  esr: z.coerce.number().min(0).optional(),

  bloodGroup: z.enum(["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]),
  bloodSugar: z.coerce.number().min(0).optional(),
  patientWeight: z.coerce.number().min(0),
  age: z.coerce.number().min(0),

  doctorId: z.string().min(1, "Select at least one doctor"),
  comments: z.string().optional(),
});

export const aiReportSchema = z.object({
  summary: z.string(),
  abnormalFindings: z.array(
    z.object({
      parameter: z.string(),
      value: z.string(),
      normalRange: z.string(),
      interpretation: z.string(),
    })
  ),
  recommendations: z.array(z.string()),
  lifestyleAdvice: z.array(z.string()),
});